### ISSUE TITLE
启用表格监测会报错

### ISSUE THREAD

**Issue by xeon-ye** [aceliuchanghong/myDeepdoc#1]
感谢您的demo，在认真学习，发现启动表格监测会出错，

**Comment by aceliuchanghong** [comment]
现阶段还没开发,欢迎pr,最近工作太忙了

**Comment by xeon-ye** [comment]
谢谢

**Comment by aceliuchanghong** [comment]
> 感谢您的demo，在认真学习，发现启动表格监测会出错，

对了,那个表格监测的命令行没问题的,只是没加到UI里面

**Comment by aceliuchanghong** [comment]
> 感谢您的demo，在认真学习，发现启动表格监测会出错，

已添加
