### ISSUE TITLE
请教，deepdoc直接输出markdown

### ISSUE THREAD

**Issue by xeon-ye** [aceliuchanghong/myDeepdoc#2]
请教个问题，如何基于输入的pdf，经过版面识别和分块OCR，最后版面重建完成还原出markdown文件

**Comment by aceliuchanghong** [comment]
> 请教个问题，如何基于输入的pdf，经过版面识别和分块OCR，最后版面重建完成还原出markdown文件

太麻烦了.没有深入了解过
